name: Prelease to NPM

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-alpha[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    name: Node ${{ matrix.node }} sample 

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: lint check
      run: npm run lint
    - name: prettier check
      run: npm run prettier:list
    - name: type check
      run: npm run tsc
    - name: publish
      - run: npm ci
      - run: npm test
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}