name: Publish to NPM

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Choose semver release'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    name: Node ${{ matrix.node }} sample 

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
    - name: npm release setup
      run: npm version ${{ github.event.inputs.version }} --no-commit-hooks --no-git-tag-version
    - name: set var
      run: 
        echo "NEW_PACKAGE_VERSION=v$(grep '"version:"' package.json | cut -d '"' -f 4 | head -n 1)" >> $GITHUB_OUTPUT
      id: new-package-version
    - name: Install dependencies
      run: npm install
    - name: lint check
      run: npm run lint 
    - name: prettier check
      run: npm run prettier:list
    - name: type check
      run: npm run tsc
    - name: build
      run: npm run build
    - name: commit
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Build ${{ steps.new-package-version.outputs.NEW_PACKAGE_VERSION }}"
        git push
    - name: release
      run: gh release create ${{ steps.new-package-version.outputs.NEW_PACKAGE_VERSION }} --draft --title ${{ steps.new-package-version.outputs.NEW_PACKAGE_VERSION }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: ci
      run: npm ci
    - name: publish
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}